ServiceHost = "0.0.0.0"
ServicePort = 8080
Token = "secret_token"

[minio]
Endpoint = "0.0.0.0:9000"
BucketName = "images"

[jwt]
Token = "drake"
ExpiresIn = "1h"

[Redis]
DialTimeout = "10s"
ReadTimeout = "10s"
